feature: added routes for views
unknownlabs/hackernews-clone pull request #4
Opened 2021-09-14 02:43 UTC by SukeruB

2021-09-14 05:42 UTC, pabloverduzco requested changes
-

2021-09-14 05:42 UTC, pabloverduzco commented on package.json
> +    "dotenv": "^10.0.0"
```suggestion
    "dotenv": "^10.0.0"
    "nodemon": "^2.0.12"
```

2021-09-14 05:42 UTC, pabloverduzco commented on src/database-connection.js
> +const {HOST,USER,PASSWORD,DATABASE,PORT} = process.env;
https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-process-env.md

2021-10-17 21:14 UTC, pabloverduzco commented on src/database-connection.js
> +}
🤔

2021-10-17 21:45 UTC, SukeruB commented on src/database-connection.js
🍆🍆🍆

2021-10-17 21:46 UTC, SukeruB reviewed
🍆🍆

2021-10-17 21:48 UTC, merged